# Generated by Django 4.0.1 on 2022-01-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipoConta', models.IntegerField(choices=[('1', 'carteira'), ('2', 'corrente'), ('3', 'poupanca')], max_length=1)),
                ('instituicaoFinanceira', models.CharField(max_length=200)),
            ],
        ),
    ]
