# Generated by Django 4.0.1 on 2022-01-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipoConta',
            field=models.CharField(choices=[('1', 'carteira'), ('2', 'corrente'), ('3', 'poupanca')], max_length=1),
        ),
    ]
