# Generated by Django 4.0.1 on 2022-01-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_conta_tipoconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
