# Generated by Django 4.0.1 on 2022-01-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_conta_numconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipoConta',
            field=models.CharField(choices=[('carteira', 'carteira'), ('corrente', 'corrente'), ('poupanca', 'poupanca')], max_length=8),
        ),
    ]
