# Generated by Django 4.0.1 on 2022-01-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0004_conta_numconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataRecebimento', models.DateField()),
                ('dataPagamentoEsperado', models.DateField()),
                ('descricao', models.TextField(max_length=250)),
                ('tipoReceita', models.CharField(choices=[('1', 'salario'), ('2', 'presente'), ('3', 'premio'), ('4', 'outros')], max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='conta.conta')),
            ],
        ),
    ]
