# Generated by Django 4.0.1 on 2022-01-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_tiporeceita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='dataPagamentoEsperado',
            new_name='dataRecebimentoEsperado',
        ),
    ]
