# Generated by Django 4.0.1 on 2022-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipoDespesa',
            field=models.CharField(choices=[('alimentacao', 'alimentacao'), ('educacao', 'educacao'), ('lazer', 'lazer'), ('moradia', 'moradia'), ('roupa', 'roupa'), ('saude', 'saude'), ('transporte', 'transporte'), ('outros', 'outros')], max_length=11),
        ),
    ]
